# En production, utilisez le backend GitHub avec Auth0
backend:
  name: github
  repo: aciderix/Cleanweb
  branch: main
  client_id: Ov23lixJWesYNuUHu8hP
  base_url: https://api.netlify.com

# Configuration des messages de commit
commit_messages:
  create: "Create {{collection}} '{{slug}}'"
  update: "Update {{collection}} '{{slug}}'"
  delete: "Delete {{collection}} '{{slug}}'"
  uploadMedia: "Upload '{{path}}'"
  deleteMedia: "Delete '{{path}}'"

# Pour le développement local, vous pouvez décommenter la ligne ci-dessous
# et commenter les lignes ci-dessus
# backend:
#   name: test-repo

# Activer l'éditeur éditorial
publish_mode: editorial_workflow

media_folder: "images/uploads" # Dossier où seront stockées les images téléchargées
public_folder: "/images/uploads" # URL publique pour les images

# La méthode la plus simple : Ne pas utiliser de webhook, car GitHub Actions
# va automatiquement s'exécuter quand un fichier dans _events est modifié

collections:
  - name: "events"
    label: "Événements"
    folder: "_events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date d'événement", name: "date", widget: "string", hint: "Exemple: Prochainement, À venir, 12 Juin 2025, etc."}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Lien", name: "link", widget: "string", default: "#contact"}
      - {label: "Texte du lien", name: "linkText", widget: "string", default: "Plus d'informations"}
      - {label: "Publication date", name: "publishDate", widget: "datetime"}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1}
  - name: "partners"
    label: "Partenaires"
    folder: "_partners"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Ordre d'affichage", name: "order", widget: "number", default: 1} 